// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package lookup

type Group struct {
	GroupID   string `json:"group_id"`
	GroupName string `json:"group_name"`
}

type Server struct {
	ServerID        int64  `json:"server_id"`
	OutputChannel   int64  `json:"output_channel"`
	GroupID         string `json:"group_id"`
	PermissionLevel int64  `json:"permission_level"`
}
