// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package lookup

import (
	"context"
)

type Querier interface {
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	DeleteGroup(ctx context.Context, groupID string) error
	DeleteServer(ctx context.Context, arg DeleteServerParams) error
	GetGroup(ctx context.Context, groupID string) (Group, error)
	GetServerCount(ctx context.Context, groupID string) (int64, error)
	GetServerGroup(ctx context.Context, serverID int64) (Group, error)
	ListGroups(ctx context.Context) ([]Group, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
}

var _ Querier = (*Queries)(nil)
