services:
  snitch-sqld:
    image: ghcr.io/tursodatabase/libsql-server:latest
    command: sqld --enable-namespaces
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      - SQLD_ADMIN_LISTEN_ADDR=0.0.0.0:9090
      - SQLD_DB_PATH=snitch.db
      - RUST_LOG=trace
      - SQL_AUTH_JWT_KEY="${PUBLIC_KEY}"
    ports:
      - ":8080"
      - ":9090"
    volumes:
      - sqld-volume:/var/lib/sqld

  snitch-sqld-proxy:
    image: nginx:alpine
    depends_on:
      - snitch-sqld
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  snitchbe:
    build:
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: cmd
        - action: rebuild
          path: internal
        - action: rebuild
          path: pkg
    # restart: unless-stopped
    image: snitchbe
    depends_on:
      - snitch-sqld-proxy
    environment:
      - LIBSQL_HOST=snitch-sqld-proxy
      - LIBSQL_PORT=8080
      - LIBSQL_ADMIN_PORT=9090
      - LIBSQL_AUTH_KEY=${PRIVATE_KEY}
    ports:
      - 4200:4200

volumes:
  sqld-volume:
  go-cache:
