networks:
  snitch-network:
    ipam:
      config:
        - subnet: 219.219.219.64/26

services:
  snitch-sqld:
    image: ghcr.io/tursodatabase/libsql-server:latest
    command: sqld --enable-namespaces
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8080
      - SQLD_ADMIN_LISTEN_ADDR=0.0.0.0:9090
      - SQLD_DB_PATH=snitch.db
      - RUST_LOG=debug
      - SQL_AUTH_JWT_KEY="${PUBLIC_KEY}"
    ports:
      - ":8080"
      - ":9090"
    volumes:
      - sqld-volume:/var/lib/sqld
    networks:
      - snitch-network

  dnsmasq:
    image: strm/dnsmasq
    volumes:
      - ./proxy/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      snitch-network:
        ipv4_address: 219.219.219.126

  snitch-sqld-proxy:
    image: nginx:alpine
    depends_on:
      - snitch-sqld
      - dnsmasq
    ports:
      - 80:80
      - 90:90
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      snitch-network:
        ipv4_address: 219.219.219.125

  snitchbe:
    build:
      dockerfile: Containerfile
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: cmd
        - action: rebuild
          path: internal
        - action: rebuild
          path: pkg
    # restart: unless-stopped
    image: snitchbe
    depends_on:
      - snitch-sqld-proxy
    environment:
      - LIBSQL_HOST=snitch-sqld-proxy
      - LIBSQL_PORT=80
      - LIBSQL_ADMIN_PORT=90
      - LIBSQL_AUTH_KEY=${PRIVATE_KEY}
    ports:
      - 4200:4200
    networks:
      - snitch-network
    dns:
      - 219.219.219.126 # dnsmasq

volumes:
  sqld-volume:
