// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package group

import (
	"context"
)

type Querier interface {
	CreateAllTables(ctx context.Context) error
	GetAllReports(ctx context.Context) ([]GetAllReportsRow, error)
}

var _ Querier = (*Queries)(nil)
