// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package group

type Report struct {
	ReportID       int64  `json:"report_id"`
	ReportText     string `json:"report_text"`
	ReporterID     int64  `json:"reporter_id"`
	ReportedUserID int64  `json:"reported_user_id"`
	OriginServerID int64  `json:"origin_server_id"`
}

type Server struct {
	ServerID int64 `json:"server_id"`
}

type User struct {
	UserID int64 `json:"user_id"`
}
