// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package group

import (
	"context"
)

type Querier interface {
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateServer(ctx context.Context, serverID int64) error
	CreateUser(ctx context.Context, userID int64) error
	DeleteReport(ctx context.Context, reportID int64) error
	GetReport(ctx context.Context, reportID int64) (Report, error)
	ListUserReports(ctx context.Context, reportedUserID int64) ([]ListUserReportsRow, error)
	UpdateReport(ctx context.Context, arg UpdateReportParams) error
}

var _ Querier = (*Queries)(nil)
