// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Report struct {
	ReportID       int    `json:"report_id"`
	ReportText     string `json:"report_text"`
	ReporterID     int    `json:"reporter_id"`
	ReportedUserID int    `json:"reported_user_id"`
	OriginServerID int    `json:"origin_server_id"`
}

type Server struct {
	ServerID int `json:"server_id"`
}

type User struct {
	UserID int `json:"user_id"`
}
