// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddServer(ctx context.Context, serverID int) error
	AddUser(ctx context.Context, userID int) error
	CreateReport(ctx context.Context, arg CreateReportParams) (int, error)
	GetAllReports(ctx context.Context) ([]GetAllReportsRow, error)
}

var _ Querier = (*Queries)(nil)
