global:
  checkNewVersion: true
  sendAnonymousUsage: false

accessLog:
  addInternals: true

entryPoints:
  web-8080:
    address: ":8080"
  web-9090:
    address: ":9090"

http:
  services:
    snitch-sqld:
      loadBalancer:
        servers:
          - url: "http://snitch-sqld"

  routers:
    Router-1:
      rule: "HostRegexp(`{subdomain:[a-z0-9-.]+}\\.snitch-sqld`)"
      service: "snitch-sqld"
      entryPoints:
        - "web-8080"
      middlewares:
        - "redirect-sqld"
        - "add-host-header"
    Router-2:
      rule: "!HostRegexp(`{subdomain:[a-z0-9-]+}\\.snitch-sqld`)"
      service: "snitch-sqld"
      entryPoints:
        - "web-8080"
        - "web-9090"

  middlewares:
    add-host-header:
      headers:
        customRequestHeaders:
          Host: "{subdomain}.db"
    redirect-sqld:
      redirectRegex:
        regex: "^http://([a-z0-9-]+)\\.snitch-sqld(.*)"
        replacement: "http://snitch-sqld${2}"
        permanent: true
log:
  level: TRACE
# api:
#   insecure: true
#   dashboard: true
